# Melgan generator with PWGAN Discriminator bigger version

datasets:
    [
        {
            name: "tts_gen",
            path: "/home/erogol/Data/LJSpeech-1.1/pwgan-v2/",
            metafile_train: "metadata.txt",
            metafile_val: null,
            stats: null
        }
    ]

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
audio:
  sample_rate: 22050     # Sampling rate.
  num_mels: 80
  num_freq: 1025           # FFT size.
  frame_length_ms: 50            # Hop size.
  frame_shift_ms: 12.5         # Window length.
  preemphasis: 0.98
  min_level_db: -100
  ref_level_db: 20
  signal_norm: true
  symmetric_norm: true
  max_norm: 4
  clip_norm: true
  mel_fmin: 0.0
  mel_fmax: 8000.0
  do_trim_silence: true
  sound_norm: false
  trim_db: 60

###########################################################
#         GENERATOR NETWORK ARCHITECTURE SETTING          #
###########################################################
generator_type: "MelGANGenerator" # Generator type.
generator_params:
    in_channels: 80               # Number of input channels.
    out_channels: 1               # Number of output channels.
    kernel_size: 7                # Kernel size of initial and final conv layers.
    channels: 512                 # Initial number of channels for conv layers.
    upsample_scales: [5, 5, 11]   # List of Upsampling scales.
    stack_kernel_size: 3          # Kernel size of dilated conv layers in residual stack.
    stacks: 3                     # Number of stacks in a single residual stack module.
    use_weight_norm: True         # Whether to use weight normalization.
    use_causal_conv: False        # Whether to use causal convolution.
###########################################################
#       DISCRIMINATOR NETWORK ARCHITECTURE SETTING        #
###########################################################
discriminator_type: "ResidualParallelWaveGANDiscriminator"
discriminator_params:
    in_channels: 1        # Number of input channels.
    out_channels: 1       # Number of output channels.
    kernel_size: 3        # Number of output channels.
    layers: 30            # Number of conv layers.
    stacks: 3             # Number of stacks i.e., dilation cycles.
    residual_channels: 32 # Number of channels in residual conv.
    gate_channels: 64     # Number of channels in gated conv.
    skip_channels: 32     # Number of channels in skip conv.
    dropout: 0.0          # Dropout rate. 0.0 means no dropout applied.
    use_weight_norm: true # Whether to use weight norm.
                          # If set to true, it will be applied to all of the conv layers.
    nonlinear_activation: "LeakyReLU" # Nonlinear function after each conv.
    nonlinear_activation_params:      # Nonlinear function parameters
        negative_slope: 0.2           # Alpha in LeakyReLU.

###########################################################
#               ADVERSARIAL LOSS SETTING                  #
###########################################################
lambda_adv: 4.0  # Loss balancing coefficient.

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 7              # Batch size.
batch_max_steps: 28820    # Length of each audio in batch. Make sure dividable by hop_size.
pin_memory: true           # Whether to pin memory in Pytorch DataLoader.
num_workers: 2             # Number of workers in Pytorch DataLoader
remove_short_samples: true # Whether to remove samples the length of which are less than batch_max_steps.
allow_cache: true
augment: false             # augment spectragrams with random noise

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
generator_optimizer_params:
    lr: 0.0001             # Generator's learning rate.
    eps: 1.0e-6            # Generator's epsilon.
    weight_decay: 0.0      # Generator's weight decay coefficient.
generator_scheduler_params:
    step_size: 200000      # Generator's scheduler step size.
    gamma: 0.5             # Generator's scheduler gamma.
                           # At each step size, lr will be multiplied by this parameter.
generator_grad_norm: 10    # Generator's gradient norm.
discriminator_optimizer_params:
    lr: 0.00005            # Discriminator's learning rate.
    eps: 1.0e-6            # Discriminator's epsilon.
    weight_decay: 0.0      # Discriminator's weight decay coefficient.
discriminator_scheduler_params:
    step_size: 200000      # Discriminator's scheduler step size.
    gamma: 0.5             # Discriminator's scheduler gamma.
                           # At each step size, lr will be multiplied by this parameter.
discriminator_grad_norm: 1 # Discriminator's gradient norm.

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
discriminator_train_start_steps: 100000  # Number of steps to start to train discriminator.
train_max_steps: 400000           # Number of training steps.
save_interval_steps: 5000          # Interval steps to save checkpoint.
eval_interval_steps: 1000          # Interval steps to evaluate the network.
log_interval_steps: 100            # Interval steps to record the training log.

###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 4  # Number of results to be saved as intermediate results.
